---
title: "XAI 3"
author: "Natalia Hernández Cortés, Eurídice Corbí Verdú, Nicolás Nebot Silvestre"
date: "2024-05-18"
output: html_document
---

{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

XAI 3

{r}
library(randomForest)
library(ggplot2)
library(pdp)
library(gridExtra)
library(dplyr)

1. One Dimensional Partial Dependence Plot

{r}
day = read.csv('day.csv')

bikes <- day %>%
  select(dteday, workingday, holiday, season, weathersit, temp, hum, windspeed, cnt) %>%
  mutate(
    spring = ifelse(season == 2, 1, 0),
    summer = ifelse(season == 3, 1, 0),
    fall = ifelse(season == 4, 1, 0),
    MISTY = ifelse(weathersit == 2, 1, 0),
    RAIN = ifelse(weathersit == 3 | weathersit == 4, 1, 0),
    temp = temp * (max(day$temp) - min(day$temp)) + min(day$temp),
    hum = hum * (max(day$hum) - min(day$hum)) + min(day$hum),
    windspeed = windspeed * (max(day$windspeed) - min(day$windspeed)) + min(day$windspeed),
    days_since_2011 = as.numeric(difftime(as.Date(day$dteday), as.Date('2011-01-01'), units = 'days'))) %>%
  select(-season, -weathersit, -dteday)


{r}
day$season = factor(day$season)
season_one_hot = model.matrix(~ 0 + season, data = day)

misty = ifelse(day$weathersit==2,1,0)
rain = ifelse(day$weathersit %in% c(3,4),1,0)

temp = (39+8)*day$temp -8
hum = day$hum*100
windspeed = day$windspeed*67

days_since_2011 =  seq(0,365*2)
dim(day)

bikes = data.frame(day$cnt, day$workingday, day$holiday, season_one_hot[,-1], misty, rain, temp, hum, windspeed, days_since_2011)
colnames(bikes)[1:6] = c("cnt", "workingday", "holiday", "spring", "summer","fall")

{r}
X = bikes[,-6]
y = bikes[,6]

set.seed(42)  
rf_model <- randomForest(x = X, y = y, ntree = 100)

{r}
plots <- list()
features <- colnames(X)

for (feature in features) {
  pdp_unidim <- partial(rf_model, pred.var = feature, train = X, rug=TRUE)
  pdp_unidim <- as.data.frame(pdp_unidim)

  p <- ggplot(pdp_unidim, aes_string(x = feature, y = "yhat")) +
    geom_line() +
    ylim(0, 6000) +
    labs(title = paste("PDP for", feature),
         x = feature,
         y = "Predicted Bike Rentals") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    theme_minimal()
  
  plots[[feature]] <- p
}

grid1 = grid.arrange(
  plots[['days_since_2011']],
  plots[['temp']],
  ncol = 2
)

ggsave(filename = "PDP_bici_1.jpg", plot = grid1, device = "jpeg")

grid2 = grid.arrange(
  plots[['hum']],
  plots[['windspeed']],
  ncol = 2
)

ggsave(filename = "PDP_bici_2.jpg", plot = grid2, device = "jpeg")

2. Bidimensional Partial Dependence Plot

{r}
set.seed(42) 
sample_indices = sample(nrow(X), size = 500)  
X_sample = X[sample_indices, ]
y_sample = y[sample_indices]

rf_model = randomForest(x = X_sample, y = y_sample, ntree = 100)

{r}
pdp_2d <- partial(rf_model, pred.var = c("hum", "temp"), grid.resolution = 50)

pdp_2d_df <- as.data.frame(pdp_2d)

# Plot 2D Partial Dependency Plot with density distributions
bd1 = ggplot() +
  geom_tile(data = pdp_2d_df, aes(x = hum, y = temp, fill = yhat), width = 0.9, height = 0.9) +
  scale_fill_viridis_c() +
  geom_rug(data = bikes, aes(x = hum), sides = "b") +
  geom_rug(data = bikes, aes(y = temp), sides = "l") + 
  theme_minimal()

ggsave(filename = "PDP_bici_3.jpg", plot = bd1, device = "jpeg")

3. PDP to explain the price of a house

{r}
house = read.csv("kc_house_data.csv")

house = house %>% select('bedrooms', 'bathrooms', 'sqft_living', 
                         'sqft_lot','floors', 'yr_built', 'price')

X = house[,-7]
y = house[,7]

{r}
set.seed(42)  
sample_indices = sample(nrow(X), size = 1000)  
X_sample = X[sample_indices, ]
y_sample = y[sample_indices]

rf_model = randomForest(x = X_sample, y = y_sample, ntree = 100)

{r}
plots <- list()
features <- colnames(X_sample)

for (feature in features) {
  pdp_unidim <- partial(rf_model, pred.var = feature, train = X_sample)
  
  p <- ggplot(pdp_unidim, aes_string(x = feature, y = "yhat")) +
    geom_line() +
    ylim(0, 1500000) +
    labs(title = paste("PDP for", feature),
         x = feature,
         y = "Predicted Price") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    theme_minimal()
  
  plots[[feature]] <- p
}

grid1 = grid.arrange(
  plots[['bedrooms']],
  plots[['bathrooms']],
  plots[['sqft_living']],
  ncol = 3
)

ggsave(filename = "PDP_casa_1.jpg", plot = grid1, device = "jpeg")

grid2 = grid.arrange(
  plots[['sqft_lot']],
  plots[['floors']],
  plots[['yr_built']],
  ncol = 3
)

ggsave(filename = "PDP_casa_2.jpg", plot = grid2, device = "jpeg")

{r}
pdp_2d <- partial(rf_model, pred.var = c("bathrooms", "floors"), grid.resolution = 50)

pdp_2d_df <- as.data.frame(pdp_2d)

# Plot 2D Partial Dependency Plot with density distributions
g = ggplot() +
  geom_tile(data = pdp_2d_df, aes(x = bathrooms, y = floors, fill = yhat), width = 0.9, height = 0.9) +
  scale_fill_viridis_c() +
  geom_rug(data = house, aes(x = bathrooms), sides = "b") +
  geom_rug(data = house, aes(y = floors), sides = "l") + 
  theme_minimal()

ggsave(filename = "PDP_casa_3.jpg", plot = g, device = "jpeg")

